server:
  port: 6065
spring:
  datasource:
    password: root
    url: jdbc:mysql://mysql:3306/fullstack
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
     hibernate:
      format-sql: true
      dialect: org.hibernate.dialect.MySQLDialect
       
 # security:
   # user:
    #  name: Teja
     # password: Tej@77807